// ═══════════════════════════════════════════════════════════
//  India's Cloud Native Ecosystem — Data Layer
//  KCD Gujarat 2026 · Ahmedabad · Sep 19, 2026
// ═══════════════════════════════════════════════════════════

const CATEGORIES = {
  leaders:     { label: 'Leaders & Governance',     color: '#4A90D9', icon: '🟦' },
  maintainers: { label: 'Maintainers & Contributors', color: '#27AE60', icon: '🟩' },
  projects:    { label: 'Projects Born in India',   color: '#E67E22', icon: '🟧' },
  ambassadors: { label: 'Ambassadors & Advocates',  color: '#8E44AD', icon: '🟪' },
  companies:   { label: 'Companies & Startups',     color: '#E74C3C', icon: '🟥' },
  education:   { label: 'Mentorship & Education',   color: '#F1C40F', icon: '🟨' },
  community:   { label: 'Community & Events',       color: '#00BCD4', icon: '🩵' },
  diversity:   { label: 'Diversity & Inclusion',     color: '#E91E63', icon: '🩷' },
};

// City positions mapped from SVG label_points (viewBox 0 0 1000 1000)
const CITIES = {
  bangalore:  { name: 'Bengaluru',     state: 'INKA', x: 320, y: 710 },
  mumbai:     { name: 'Mumbai',        state: 'INMH', x: 240, y: 590 },
  pune:       { name: 'Pune',          state: 'INMH', x: 278, y: 615 },
  chennai:    { name: 'Chennai',       state: 'INTN', x: 410, y: 785 },
  delhi:      { name: 'Delhi / NCR',   state: 'INDL', x: 344, y: 320 },
  chandigarh: { name: 'Chandigarh',    state: 'INCH', x: 335, y: 255 },
  ahmedabad:  { name: 'Ahmedabad',     state: 'INGJ', x: 215, y: 468 },
  hyderabad:  { name: 'Hyderabad',     state: 'INTG', x: 380, y: 650 },
  kerala:     { name: 'Kerala',        state: 'INKL', x: 315, y: 855 },
  jaipur:     { name: 'Jaipur',        state: 'INRJ', x: 280, y: 370 },
  kolkata:    { name: 'Kolkata',       state: 'INWB', x: 630, y: 500 },
  nashik:     { name: 'Nashik',        state: 'INMH', x: 268, y: 568 },
  noida:      { name: 'Noida',         state: 'INUP', x: 358, y: 332 },
  national:   { name: 'Pan-India 🇮🇳',  state: null,   x: null, y: null },
};

// ═══════════════════════════════════════════════════════════
//  ENTITIES — 120+ people, projects, companies, communities
// ═══════════════════════════════════════════════════════════

const ENTITIES = [

  // ────────────────────────────────────────────────────────
  //  🟦 LEADERS & GOVERNANCE
  // ────────────────────────────────────────────────────────
  {
    id: 'nikhita', name: 'Nikhita Raghunath', symbol: 'Nr',
    category: 'leaders', city: 'bangalore', org: 'Broadcom',
    title: 'CNCF TOC Vice Chair (emeritus), K8s Steering, KubeCon Chair',
    description: 'Engineering Manager at Broadcom, Bangalore. From GSoC contributor → K8s Steering Committee → CNCF TOC Vice Chair → KubeCon India Chair. Created tech-conferences-india (714⭐).',
    highlight: 'When an Indian engineer sits on the TOC that governs 230+ CNCF projects — that\'s not consumption. That\'s leadership.',
    links: { github: 'nikhita', twitter: 'TheNikhita' },
  },
  {
    id: 'nabarun', name: 'Nabarun Pal', symbol: 'Np',
    category: 'ambassadors', city: 'bangalore', org: 'Broadcom',
    description: 'Principal SWE at Broadcom, IIT Roorkee grad. First Indian to lead a Kubernetes release (v1.21). SIG ContribEx Chair. K8s GitHub Admin. Featured in Times of India twice. KubeCon India 2024 keynote.',
    highlight: 'Unity in Diversity — KubeCon India 2024 keynote by Nabarun.',
    links: { github: 'palnabarun', twitter: 'theonlynabarun' },
  },
  {
    id: 'priyanka-saggu', name: 'Priyanka Saggu', symbol: 'Ps',
    category: 'ambassadors', city: 'national', org: 'SUSE',
    title: 'K8s v1.29 Release Lead, CNCF Award 2024 "Chop Wood, Carry Water"',
    description: 'Outreachy intern (2019, GNOME) → K8s Release Lead in ~4 years. Won CNCF Community Award 2024, K8s Community Award 2023, Google OSPB 2023. Perhaps the most compelling mentee-to-leader story in CNCF.',
    highlight: 'Five years ago she was a mentee. Today she leads Kubernetes releases. Tomorrow she\'ll be mentoring the next generation.',
    links: { github: 'Priyankasaggu11929', twitter: '_psaggu' },
  },
  {
    id: 'faseela', name: 'Faseela K', symbol: 'Fk',
    category: 'leaders', city: 'national', org: 'Ericsson',
    title: 'CNCF TOC member (current), Istio Steering Committee',
    description: 'Indian-origin, based in Germany. TOC Liaison for TAG Infrastructure AND TAG Operational Resilience. CNCF Ambassador. Program Chair Istio Meetups 2023.',
    highlight: 'India\'s voice on the current CNCF Technical Oversight Committee.',
    links: {},
  },
  {
    id: 'dims', name: 'Davanum Srinivas "Dims"', symbol: 'Dm',
    category: 'leaders', city: 'national', org: 'Nvidia',
    title: 'K8s Steering, SIG Architecture Chair, containerd maintainer',
    description: 'India-born, one of the earliest and most influential K8s contributors globally. Decades of OSS (Apache, OpenStack → K8s). Arctic Code Vault + Mars 2020 Contributor.',
    highlight: 'From Apache to Kubernetes to Mars — Dims has been building open source before it was cool.',
    links: { github: 'dims' },
  },
  {
    id: 'humble', name: 'Humble Chirammal', symbol: 'Hc',
    category: 'leaders', city: 'bangalore', org: 'Broadcom',
    title: 'K8s Storage Maintainer, CSI contributor, KCD Bengaluru founder',
    description: 'Previously Red Hat (OpenShift, GlusterFS, Ceph-CSI). Authored "Mastering KVM Virtualization." CNCF Ambassador. Founded K8s Bangalore meetup (8,000+ members). Started KCD Bangalore in 2019.',
    highlight: 'The person who bootstrapped Bangalore\'s Kubernetes community from zero.',
    links: { github: 'humblec', twitter: 'hchiramm' },
  },
  {
    id: 'divya-mohan', name: 'Divya Mohan', symbol: 'Dv',
    category: 'leaders', city: 'national', org: 'SUSE',
    title: 'K8s SIG Docs Co-Chair, KCNA exam creator, KubeCon India 2024 Co-Chair',
    description: 'Co-chaired KubeCon India 2024 (Delhi) alongside Nikhita. Won 2023 CNCF Top Documentarian Award. CHAOSS Governing Board. Google Season of Docs 2020 (CERN).',
    highlight: 'Co-chaired KubeCon India 2024 and created the KCNA certification exam.',
    links: {},
  },
  {
    id: 'priyanka-sharma', name: 'Priyanka Sharma', symbol: 'Pk',
    category: 'leaders', city: 'national', org: 'Thiink Inc',
    title: 'Former General Manager of CNCF (~2020)',
    description: 'Indian-origin. Stanford grad. Led the entire CNCF organization. Highest-ranking Indian-origin leader in CNCF history. Involved with CNCF since 2016.',
    highlight: 'An Indian-origin leader ran the entire CNCF. Let that sink in.',
    links: {},
  },
  {
    id: 'madhav', name: 'Madhav Jivrajani', symbol: 'Mj',
    category: 'leaders', city: 'national', org: 'SkyPilot/UIUC',
    title: 'K8s maintainer, SIG ContribEx Tech Lead, etcd contributor',
    description: 'Young Indian contributor → K8s maintainer while still in university. API Machinery, Scalability, Architecture SIGs.',
    highlight: 'Became a Kubernetes maintainer while still a university student.',
    links: {},
  },
  {
    id: 'alolita', name: 'Alolita Sharma', symbol: 'Al',
    category: 'leaders', city: 'national', org: 'Apple',
    title: 'OTel Governance Committee, CNCF Board member',
    description: 'Indian-origin, Silicon Valley. One of the most senior Indian-origin leaders in CNCF. Former TAG Observability co-chair. OTel C++ emeritus.',
    highlight: 'From the OpenTelemetry Governance Committee to the CNCF Board.',
    links: {},
  },
  {
    id: 'ab-periasamy', name: 'AB Periasamy', symbol: 'AB',
    category: 'leaders', city: 'chennai', org: 'MinIO',
    title: 'GlusterFS founder → MinIO CEO',
    description: 'From Tamil Nadu. Annamalai University grad. Founded GlusterFS (acquired by Red Hat), then MinIO — widely used object storage in cloud native.',
    highlight: 'Two globally used open-source storage projects from one person from Tamil Nadu.',
    links: {},
  },
  {
    id: 'hemant-kumar', name: 'Hemant Kumar', symbol: 'Hk',
    category: 'leaders', city: 'national', org: 'Red Hat',
    title: 'K8s SIG Storage Chair',
    description: 'Confirmed via K8s sigs.yaml. Leading one of the most critical Kubernetes SIGs.',
    highlight: 'Chairing K8s SIG Storage — the infrastructure layer everything depends on.',
    links: {},
  },

  // ────────────────────────────────────────────────────────
  //  🟩 MAINTAINERS & CONTRIBUTORS
  // ────────────────────────────────────────────────────────
  {
    id: 'vyom', name: 'Vyom Yadav', symbol: 'Vy',
    category: 'maintainers', city: 'chandigarh', org: 'Canonical',
    title: 'K8s v1.34 Release Lead, K8s Security Response Committee, Kyverno, KubeArmor',
    description: 'One of the youngest K8s Release Leads. Google OSPB. CNCF Ambassador. MS at NYU Tandon, from Chandigarh. GSoC alum → maintainer → release lead.',
    highlight: 'Final-year student from Chandigarh → K8s Release Lead. The flywheel in action.',
    links: { github: 'vyomyadav', twitter: 'VyomYadav' },
  },
  {
    id: 'sanskar', name: 'Sanskar Jaiswal', symbol: 'Sj',
    category: 'maintainers', city: 'bangalore', org: 'Kong',
    title: 'Flux Core Maintainer (CNCF Graduated)',
    description: 'Indian maintainer of a CNCF Graduated project. Based in Bangalore.',
    highlight: 'A Graduated CNCF project with an Indian core maintainer.',
    links: {},
  },
  {
    id: 'vishal', name: 'Vishal Choudhary', symbol: 'Vc',
    category: 'maintainers', city: 'national', org: 'Chainguard',
    title: 'Kyverno maintainer, Knative, Sigstore, Cosign',
    description: 'LFX mentee → Top 3 all-time LFX contributor (6,168 contributions). Spoke at KubeCon India 2024 & KubeDay 2023.',
    highlight: 'From LFX mentee to top-3 contributor of ALL TIME across all of CNCF.',
    links: {},
  },
  {
    id: 'pranshu', name: 'Pranshu Srivastava', symbol: 'Pv',
    category: 'maintainers', city: 'bangalore', org: 'Red Hat',
    title: 'K8s SIG Instrumentation Co-Chair, Prometheus maintainer',
    description: 'CNCF Ambassador. Dual leadership: K8s SIG + CNCF project maintainer simultaneously.',
    highlight: 'Chairing a K8s SIG and maintaining Prometheus — dual leadership.',
    links: { github: 'PranshuSrivastava' },
  },
  {
    id: 'ganesh', name: 'Ganesh Vernekar', symbol: 'Gv',
    category: 'maintainers', city: 'national', org: 'Grafana Labs',
    title: 'Prometheus TSDB maintainer, Thanos contributor',
    description: 'Core Prometheus contributor focused on the TSDB (time-series database) layer. Works at Grafana Labs.',
    highlight: 'Maintaining the storage engine of the world\'s most popular monitoring system.',
    links: {},
  },
  {
    id: 'rohit-agrawal', name: 'Rohit Agrawal', symbol: 'Ra',
    category: 'maintainers', city: 'national', org: 'Databricks',
    title: 'Envoy Senior Maintainer + Security Team, Argo Rollouts reviewer',
    description: 'Cross-project superstar — Envoy Senior Maintainer AND Argo Rollouts reviewer simultaneously. Extremely rare dual maintainership.',
    highlight: 'One of the very few people maintaining TWO major CNCF projects simultaneously.',
    links: {},
  },
  {
    id: 'prem-saraswat', name: 'Prem Saraswat', symbol: 'Pm',
    category: 'maintainers', city: 'national', org: 'Red Hat',
    title: 'Thanos Core Maintainer',
    description: 'Core maintainer of Thanos — highly available Prometheus setup used by the largest enterprises.',
    highlight: 'Core maintainer of Thanos.',
    links: {},
  },
  {
    id: 'savitha', name: 'Savitha Raghunathan', symbol: 'Sv',
    category: 'maintainers', city: 'national', org: 'Red Hat',
    title: 'K8s, K8s-client, K8s-CSI, OpenShift, Konveyor maintainer',
    description: 'GenAI eval frameworks + migration tooling. Broad K8s ecosystem maintainer.',
    highlight: 'Maintaining K8s client libraries that millions of applications depend on.',
    links: {},
  },
  {
    id: 'rama-chavali', name: 'Rama Chavali', symbol: 'Rc',
    category: 'maintainers', city: 'national', org: 'Salesforce',
    title: 'Istio WG Networking Lead',
    description: 'Leading the Networking Working Group in Istio — one of the largest CNCF service mesh projects.',
    highlight: 'Leading Istio networking — the service mesh that powers enterprise microservices.',
    links: {},
  },
  {
    id: 'aditi-ghag', name: 'Aditi Ghag', symbol: 'Ag',
    category: 'maintainers', city: 'national', org: 'Isovalent',
    title: 'Cilium committer',
    description: 'One of 4 Indian Cilium committers. Cilium powers networking for major cloud providers.',
    highlight: 'Building the eBPF-powered networking layer of the cloud.',
    links: {},
  },
  {
    id: 'soumya-ghosh', name: 'Soumya Ghosh Dastidar', symbol: 'Sg',
    category: 'maintainers', city: 'national', org: 'Intuit',
    title: 'Argo CD Approver',
    description: 'Part of the strong Indian presence in the Argo project — 14+ active and alumni contributors.',
    highlight: 'Indian engineers are deeply embedded in Argo — 14+ contributors.',
    links: {},
  },

  // ────────────────────────────────────────────────────────
  //  🟧 PROJECTS BORN IN INDIA
  // ────────────────────────────────────────────────────────
  {
    id: 'kyverno', name: 'Kyverno', symbol: 'Ky',
    category: 'projects', city: 'national', org: 'Nirmata',
    title: 'K8s-native policy engine · CNCF Graduated 🎓',
    description: 'Created by Nirmata (Jim Bugwadia, Indian-origin). CNCF Graduated (Mar 2026) — same level as Kubernetes, Prometheus, Envoy. 7M+ monthly downloads, 3,711 contributors.',
    highlight: 'This is what "created in India, trusted globally" looks like.',
    links: { github: 'kyverno/kyverno', web: 'https://kyverno.io' },
  },
  {
    id: 'litmuschaos', name: 'LitmusChaos', symbol: 'Lc',
    category: 'projects', city: 'bangalore', org: 'Harness (ex-MayaData)',
    title: 'Chaos engineering for K8s · CNCF Incubating ⬆️',
    description: 'Created in Bangalore. 18 of ~21 maintainers are Indian! Uma Mukkara, Karthik Satchitanand, Amit Kumar Das. 5,600+ GitHub stars.',
    highlight: '18 of 21 maintainers are Indian. This is India\'s chaos engineering gift to the world.',
    links: { github: 'litmuschaos/litmus' },
  },
  {
    id: 'kubearmor', name: 'KubeArmor', symbol: 'Ka',
    category: 'projects', city: 'bangalore', org: 'AccuKnox',
    title: 'K8s runtime security · CNCF Sandbox 📦',
    description: 'Created by AccuKnox, India. 9 of 11 maintainers are Indian! Rahul Jadhav + 8 more. 977 contributors (+82% YoY). Two maintainers work at CERN.',
    highlight: '9 of 11 maintainers are Indian. Two of them work at CERN.',
    links: { github: 'kubearmor/KubeArmor' },
  },
  {
    id: 'openebs', name: 'OpenEBS', symbol: 'Oe',
    category: 'projects', city: 'bangalore', org: 'DataCore (ex-MayaData)',
    title: 'K8s storage · CNCF Sandbox 📦',
    description: 'Created in Bangalore. First commit Aug 2016 — one of the oldest K8s storage projects. Kiran Mova (founder). 1,055 contributors. Est. value $116.7M.',
    highlight: 'One of the oldest Kubernetes storage projects, born in Bangalore.',
    links: { github: 'openebs/openebs' },
  },
  {
    id: 'kubelasti', name: 'KubeElasti', symbol: 'Ke',
    category: 'projects', city: 'national', org: 'TrueFoundry',
    title: 'K8s scale-to-zero · CNCF Sandbox 📦 (Jan 2026)',
    description: 'Founded by IIT alumni: Nikunj Bajaj (ex-Facebook ML Lead), Abhishek Choudhary (ex-Facebook Sr Staff), Anuraag Gutgutia (ex-WorldQuant VP). K8s-native scale-to-zero with smart proxy. Community meetings at 19:00 IST.',
    highlight: 'The newest India-born CNCF project — scale-to-zero for Kubernetes.',
    links: { github: 'truefoundry/kubelasti' },
  },
  {
    id: 'devtron', name: 'Devtron', symbol: 'Dt',
    category: 'projects', city: 'national', org: 'Devtron Labs',
    title: 'AI-native K8s management · CNCF Landscape',
    description: 'Indian-founded. 15K+ installations. 4.9K stars. CNCF member since Jan 2023. Note: Landscape listing, not official Sandbox project.',
    highlight: 'Indian-built K8s management platform with 15K+ installations.',
    links: { github: 'devtron-labs/devtron' },
  },
  {
    id: 'parseable', name: 'Parseable', symbol: 'Pb',
    category: 'projects', city: 'bangalore', org: 'Cloudnatively Services',
    title: 'Rust-based observability · CNCF Landscape',
    description: 'Bengaluru-based. Rust-based, OTel-native observability. Note: Landscape listing, not official Sandbox project.',
    highlight: 'Rust-based observability — made in Bengaluru.',
    links: { github: 'parseablehq/parseable' },
  },

  // ────────────────────────────────────────────────────────
  //  🟪 AMBASSADORS & ADVOCATES
  // ────────────────────────────────────────────────────────
  {
    id: 'saiyam', name: 'Saiyam Pathak', symbol: 'Sp',
    category: 'leaders', city: 'chandigarh', org: 'vCluster / Kubesimplify',
    title: 'TAG OpRes Chair, Kubestronaut, KubeCon India 2026 Program Chair',
    description: 'Founded Kubesimplify (100K+ community, 50K+ YouTube). TAG Operational Resilience Chair. 5 open-source tools. The most visible cloud-native advocate in India.',
    highlight: 'From content creator to TAG Chair — Saiyam built India\'s biggest cloud-native community.',
    links: { github: 'saiyam1814', twitter: 'saiyampathak' },
  },
  {
    id: 'hrittik', name: 'Hrittik Roy', symbol: 'Hr',
    category: 'ambassadors', city: 'kolkata', org: 'vCluster Labs',
    title: 'KubeCon Program Committee, MCP Dev Summit keynote',
    description: 'Multiple KubeCon Program Committee roles. Keynote speaker at MCP Dev Summit.',
    highlight: 'On the KubeCon Program Committee — deciding what the world sees on stage.',
    links: { github: 'hrittikhere' },
  },
  {
    id: 'rohit-ghumare', name: 'Rohit Ghumare', symbol: 'Rg',
    category: 'ambassadors', city: 'mumbai', org: 'motia',
    title: 'CNCF Marketing Chair 2025, Google DevExpert, Docker Captain',
    description: 'Organizer KCD UK, KCD Mumbai, DevOpsDays Bengaluru. Triple community hat: CNCF Ambassador + Google DevExpert + Docker Captain.',
    highlight: 'CNCF Marketing Chair — shaping how the world sees cloud native.',
    links: { github: 'ghumare64' },
  },
  {
    id: 'saloni', name: 'Saloni Narang', symbol: 'Sn',
    category: 'ambassadors', city: 'chandigarh', org: 'Kubesimplify',
    title: 'Docker Captain, Kubesimplify co-founder, KubeCon speaker',
    description: 'Co-founded Kubesimplify with Saiyam. Docker Captain. Spoke at KubeCon Paris + KubeCon NA.',
    highlight: 'Co-building India\'s biggest cloud-native education platform.',
    links: {},
  },
  {
    id: 'arsh', name: 'Arsh Sharma', symbol: 'As',
    category: 'ambassadors', city: 'chandigarh', org: 'MetalBear',
    title: 'K8s Contributor Award, cert-manager & Kyverno contributor',
    description: 'K8s 1.25 CI Signal Lead. cert-manager and Kyverno contributor from Chandigarh.',
    highlight: 'Chandigarh\'s open-source pipeline keeps producing — Arsh is proof.',
    links: {},
  },
  {
    id: 'yash-pimple', name: 'Yash Pimple', symbol: 'Yp',
    category: 'ambassadors', city: 'mumbai', org: 'Chainguard',
    title: 'K8sGPT, Keptn, Kyverno contributor, Cloud-native Thane co-organizer',
    description: 'Student turned multi-project contributor. Co-organizes Cloud Native Thane meetup.',
    highlight: 'Still a student, already contributing to K8sGPT, Keptn, and Kyverno.',
    links: {},
  },
  {
    id: 'barun', name: 'Barun Acharya', symbol: 'Ba',
    category: 'ambassadors', city: 'delhi', org: 'AccuKnox',
    title: 'KubeArmor maintainer, GSoC + LFX contributor',
    description: 'Active KubeArmor maintainer and community contributor. GSoC and LFX alumni.',
    highlight: 'From mentorship programs to maintaining a CNCF project.',
    links: {},
  },
  {
    id: 'sagar-utekar', name: 'Sagar Utekar', symbol: 'Su',
    category: 'ambassadors', city: 'pune', org: 'CrowdStrike',
    title: 'CNCF Ambassador, Golden Kubestronaut, KCD Gujarat 2026 Speaker',
    description: 'Site Reliability & Cloud Engineer at CrowdStrike, Pune. CNCF Ambassador. Golden Kubestronaut — passed all 15 CNCF certifications + LFCS. Speaker at KCD Gujarat 2026. 7+ years in SRE, platform engineering, and infrastructure automation.',
    highlight: 'Golden Kubestronaut, CNCF Ambassador, and your keynote speaker today at KCD Gujarat 2026.',
    links: {},
  },
  {
    id: 'sonali', name: 'Sonali Srivastava', symbol: 'So',
    category: 'leaders', city: 'mumbai', org: 'InfraCloud',
    title: 'Sr. Developer Advocate, Co-chair KubeCon India 2026, CNCF Ambassador',
    description: 'Co-chairing KubeCon India 2026. CNCG Organizer @ Women in Cloud Native. Keynote Speaker at KubeCon India. Author of LFS255 (Linux Foundation). Outreachy 2022 alumna.',
    highlight: 'From Outreachy intern to KubeCon India Co-chair and Keynote Speaker — building the path for women in cloud native.',
    links: { github: 'cerebro1' },
  },
  {
    id: 'rahul-jadhav', name: 'Rahul Jadhav', symbol: 'Rj',
    category: 'ambassadors', city: 'bangalore', org: 'AccuKnox',
    title: 'KubeArmor maintainer, K8s Security Bangalore Meetup',
    description: 'Runs K8s Cloud Native Security Bangalore Meetup. IETF Standards working groups.',
    highlight: 'Building cloud-native security from Bangalore to the IETF.',
    links: {},
  },
  {
    id: 'fazlur', name: 'Fazlur Rahman Khan', symbol: 'Fz',
    category: 'ambassadors', city: 'bangalore', org: 'The Linux Foundation',
    title: 'Authors CKA/CKAD/CKS courses at Linux Foundation',
    description: 'Kubestronaut. First LF technical trainer based in India. 20+ years experience. Authors the official certification courses millions study.',
    highlight: 'The person who writes the CKA exam you studied for.',
    links: {},
  },
  {
    id: 'atulpriya', name: 'Atulpriya Sharma', symbol: 'At',
    category: 'ambassadors', city: 'hyderabad', org: 'InfraCloud Technologies',
    title: 'CNCF Hyderabad organizer, content creator',
    description: 'Organizer of CNCF Hyderabad chapter. KubeCon India 2025 Co-Chair. DevRel, content creator, Twitter spaces host.',
    highlight: 'Building Hyderabad\'s cloud-native community from the ground up.',
    links: {},
  },
  {
    id: 'bhavani', name: 'Bhavani Indukuri', symbol: 'Bi',
    category: 'ambassadors', city: 'hyderabad', org: 'Zscaler',
    title: 'Women in Cloud Native organizer, KubeCon India 2025 Co-Chair',
    description: 'Women in Cloud Native organizer. Migrated enterprise infra to K8s at scale at Zscaler.',
    highlight: 'Combining enterprise-scale K8s migration with diversity advocacy.',
    links: {},
  },
  {
    id: 'shivay', name: 'Shivay Lamba', symbol: 'Sl',
    category: 'ambassadors', city: 'delhi', org: 'Independent',
    title: 'GSoC Admin & Mentor (Jenkins/Kubeflow), TensorflowJS SIG',
    description: 'From New Delhi. GSoC admin and mentor for Jenkins and Kubeflow. CNCF Service Mesh mentor.',
    highlight: 'Mentoring the next generation from Delhi.',
    links: {},
  },
  {
    id: 'ebin', name: 'Ebin Babu', symbol: 'Eb',
    category: 'ambassadors', city: 'kerala', org: 'Stackgenie.io',
    title: 'CNCG Trivandrum lead, devopsmalayalam.io co-founder',
    description: 'Co-founded devopsmalayalam.io, leads CNCF Trivandrum chapter. Organized 100+ events from Kerala.',
    highlight: '100+ events from Kerala — proving cloud native happens everywhere in India.',
    links: {},
  },
  {
    id: 'manikandan', name: 'Manikandan K', symbol: 'Mk',
    category: 'ambassadors', city: 'chennai', org: 'Independent',
    title: 'Cloud Native Chennai organizer (4+ years), GCP Architect',
    description: '15+ years experience. Organized Cloud Native Chennai for 4+ years.',
    highlight: 'Four years of consistent community building in Chennai.',
    links: {},
  },
  {
    id: 'kaiwalya', name: 'Kaiwalya Koparkar', symbol: 'Kp',
    category: 'ambassadors', city: 'nashik', org: 'Gravitee.io',
    title: 'Founded Cloud Native Nashik',
    description: 'Founded the CNCF chapter in Nashik — a Tier-2 city. KCNA/CKA/CKAD certified.',
    highlight: 'Cloud native doesn\'t live only in metros — Nashik proves it.',
    links: {},
  },
  {
    id: 'ronit', name: 'Ronit Banerjee', symbol: 'Rb',
    category: 'ambassadors', city: 'kolkata', org: 'Keysight',
    title: 'Cloud Native Hooghly lead, GSoC Mentor, UbuCon Global Committee',
    description: 'Leads Cloud Native Hooghly (West Bengal). GSoC Mentor at DBpedia.',
    highlight: 'East India\'s cloud-native flag bearer.',
    links: {},
  },
  {
    id: 'swastik', name: 'Swastik Gour', symbol: 'Sw',
    category: 'ambassadors', city: 'jaipur', org: 'Student',
    title: 'CNCF Jaipur lead organizer, GSoC + LFX mentee (Kyverno)',
    description: 'Student leading Jaipur\'s CNCF chapter. GSoC and LFX mentee on Kyverno.',
    highlight: 'A student running Jaipur\'s cloud-native chapter — the grassroots engine.',
    links: {},
  },
  {
    id: 'sreejith', name: 'Sreejith Anujan', symbol: 'Sr',
    category: 'ambassadors', city: 'kerala', org: 'Independent',
    title: 'FOSS contributor since 2001, first KCD + DevOpsDays in Kerala',
    description: 'Organized the first KCD and DevOpsDays in Kerala. FOSS contributor for 25+ years.',
    highlight: '25 years in open source — organized Kerala\'s first KCD and DevOpsDays.',
    links: {},
  },
  {
    id: 'shivlal', name: 'Shivlal Sharma', symbol: 'Ss',
    category: 'ambassadors', city: 'ahmedabad', org: 'Independent',
    title: 'CNCG Ahmedabad organizer, CKA certified',
    description: 'Organizer of the Cloud Native Community Group in Ahmedabad. CKA certified.',
    highlight: 'Building cloud native right here in Ahmedabad.',
    links: {},
  },
  {
    id: 'aditya-soni', name: 'Aditya Soni', symbol: 'Ad',
    category: 'ambassadors', city: 'jaipur', org: 'Independent',
    title: 'CNCG Jaipur lead, AWS Community Builder/Leader',
    description: 'Lead organizer of CNCF Jaipur chapter. AWS Community Builder and Leader.',
    highlight: 'Jaipur\'s cloud-native champion.',
    links: {},
  },
  {
    id: 'harsh-manvar', name: 'Harsh Manvar', symbol: 'Hm',
    category: 'ambassadors', city: 'ahmedabad', org: 'Independent',
    title: 'Docker Captain, Top K8s answerer on StackOverflow worldwide',
    description: 'Top Kubernetes answerer worldwide on StackOverflow. Docker Captain.',
    highlight: 'When the world has a K8s question on StackOverflow, an Indian answers.',
    links: {},
  },
  {
    id: 'sandeep-kanabar', name: 'Sandeep Kanabar', symbol: 'Sk',
    category: 'leaders', city: 'ahmedabad', org: 'Independent',
    description: 'Key organizer behind KCD Gujarat 2026. Building the cloud-native community in Ahmedabad.',
    highlight: 'The person who made KCD Gujarat happen. This event is here because of organizers like Sandeep.',
    links: {},
  },
  {
    id: 'ram-iyengar', name: 'Ram Iyengar', symbol: 'Ri',
    category: 'leaders', city: 'chennai', org: 'Cloud Foundry',
    title: 'Cloud Foundry advocate, cross-ecosystem bridge',
    description: 'From Chennai. Bridges Cloud Foundry and CNCF communities. A connector across ecosystems.',
    highlight: 'Bridging ecosystems — Cloud Foundry meets CNCF in Chennai.',
    links: {},
  },
  {
    id: 'nitish', name: 'Nitish Kumar', symbol: 'Nk',
    category: 'maintainers', city: 'national', org: 'Akuity',
    title: 'ArgoCD Maintainer, CNCF Ambassador, LFX Kubernetes 2023',
    description: 'Maintainer of ArgoCD (CNCF graduated). Engineering at Akuity. CNCF Ambassador. LFX mentee turned Kubernetes contributor in 2023. Based in Punjab.',
    highlight: 'From LFX mentee to ArgoCD maintainer — shipping one of the most widely deployed GitOps tools in the CNCF ecosystem.',
    links: { github: 'nitishfy' },
  },

  // ────────────────────────────────────────────────────────
  //  🟥 COMPANIES & STARTUPS
  // ────────────────────────────────────────────────────────
  {
    id: 'infracloud', name: 'InfraCloud Technologies', symbol: 'IC',
    category: 'companies', city: 'pune', org: 'Vishal Biyani & Girish Shilamkar',
    title: 'India\'s first K8s partner (2017), Fission, Botkube',
    description: 'Founded in Pune. India\'s first K8s partner. 51 CKAs, 19 CKADs, 4 CKS holders. Created Fission (serverless). Won Stratus Award 2023.',
    highlight: 'India\'s first Kubernetes partner — and still leading.',
    links: { web: 'https://infracloud.io' },
  },
  {
    id: 'nirmata', name: 'Nirmata', symbol: 'Nm',
    category: 'companies', city: 'national', org: 'Jim Bugwadia (Indian-origin)',
    title: 'Created Kyverno (CNCF Graduated)',
    description: 'Indian-origin founder. Created Kyverno — 7M+ monthly downloads, CNCF Graduated.',
    highlight: 'The company behind the only India-born CNCF Graduated project.',
    links: { web: 'https://nirmata.com' },
  },
  {
    id: 'flipkart', name: 'Flipkart', symbol: 'Fp',
    category: 'companies', city: 'bangalore', org: 'Walmart',
    title: 'CNCF Reference Architecture, End User Case Study Award ⭐',
    description: 'Published on architecture.cncf.io. 2,000+ chaos experiments with LitmusChaos. CNCF End User Case Study Award.',
    highlight: 'The global community is literally learning from how an Indian company runs infrastructure.',
    links: {},
  },
  {
    id: 'razorpay', name: 'Razorpay', symbol: 'Rz',
    category: 'companies', city: 'bangalore', org: '',
    title: '7,000+ K8s nodes, $180B payment volume',
    description: 'Bangalore. 7,000+ K8s nodes. $180B annualized payment volume. Uses Kyverno for RBI compliance. CNCF case study.',
    highlight: '7,000 Kubernetes nodes processing India\'s payments.',
    links: {},
  },
  {
    id: 'hasura', name: 'Hasura', symbol: 'Hs',
    category: 'companies', city: 'bangalore', org: 'Tanmai Gopal & Rajoshi Ghosh',
    title: 'Instant GraphQL APIs, $135M+ raised, CNCF Landscape',
    description: 'Bangalore/SF. Co-founded by Tanmai Gopal & Rajoshi Ghosh. $135M+ raised. Hasura GraphQL Engine → instant GraphQL APIs. Millions of developers.',
    highlight: 'From Bangalore to millions of developers worldwide — Hasura put India on the GraphQL map.',
    links: { github: 'hasura/graphql-engine' },
  },
  {
    id: 'zerodha', name: 'Zerodha', symbol: 'Zr',
    category: 'companies', city: 'bangalore', org: '',
    title: 'India\'s largest broker — deliberately anti-cloud, self-hosted',
    description: 'Uses Prometheus/Grafana/VictoriaMetrics self-hosted. No K8s. "Simple scales." India\'s most admired eng team for doing more with less.',
    highlight: 'Proof that cloud-native thinking matters even when you don\'t use K8s.',
    links: {},
  },
  {
    id: 'signoz', name: 'SigNoz', symbol: 'Sz',
    category: 'companies', city: 'national', org: 'YC-W21',
    title: 'Open-source APM, OpenTelemetry-native',
    description: 'Indian-founded (YC-W21). Open-source observability platform. OTel-native. Srikanth Chekuri (OTel Python approver) is from SigNoz.',
    highlight: 'Indian-founded, YC-backed, open-source observability.',
    links: { github: 'SigNoz/signoz' },
  },
  {
    id: 'accuknox', name: 'AccuKnox', symbol: 'Ak',
    category: 'companies', city: 'bangalore', org: '',
    title: 'Created KubeArmor (CNCF Sandbox)',
    description: 'India-based. Created KubeArmor. 9 of 11 maintainers are Indian.',
    highlight: 'The company behind KubeArmor — 9 of 11 maintainers are Indian.',
    links: {},
  },
  {
    id: 'harness', name: 'Harness (ex-MayaData)', symbol: 'Ha',
    category: 'companies', city: 'bangalore', org: '',
    title: 'Created LitmusChaos + OpenEBS',
    description: 'Bangalore. Created LitmusChaos (Incubating) + OpenEBS (Sandbox). 18+ Indian maintainers across both projects.',
    highlight: 'Two CNCF projects from one Bangalore company.',
    links: {},
  },
  {
    id: 'nudgebee', name: 'NudgeBee', symbol: 'Nb',
    category: 'companies', city: 'national', org: 'Kalaari-backed',
    title: 'AI CloudOps startup',
    description: 'AI-powered cloud operations. Backed by Kalaari Capital.',
    highlight: 'India\'s next wave — AI meets cloud operations.',
    links: {},
  },
  {
    id: 'sherlocks-ai', name: 'Sherlocks AI', symbol: 'Sh',
    category: 'companies', city: 'national', org: 'Founded 2025',
    title: 'AI SRE startup',
    description: 'Founded in 2025. AI-powered site reliability engineering.',
    highlight: 'AI SRE — the newest addition to India\'s cloud-native startup scene.',
    links: {},
  },

  // ────────────────────────────────────────────────────────
  //  🟨 MENTORSHIP & EDUCATION
  // ────────────────────────────────────────────────────────
  {
    id: 'gsoc', name: 'GSoC India', symbol: 'GS',
    category: 'education', city: 'national', org: 'Google',
    title: 'India = #1 country ALL-TIME in GSoC participation',
    description: '2018 peak: 605 Indian students accepted — 6x more than the USA (104). Top institutions: IIT Roorkee (35), IIIT Hyderabad (32), BITS Pilani (23). ~40-50% of all GSoC participants globally.',
    highlight: 'India sends more GSoC contributors than any other country in the world. 6x the USA.',
    links: { web: 'https://summerofcode.withgoogle.com' },
  },
  {
    id: 'lfx', name: 'LFX Mentorship', symbol: 'LF',
    category: 'education', city: 'national', org: 'Linux Foundation',
    title: 'India = ~30-50% of ALL LFX mentees · 25 mentees → maintainers',
    description: '187 mentorships in 2025 (record). 40,000 contributions in 2025 (4x since 2021). 25 LFX mentees became CNCF project maintainers since 2020. 3 of top 4 all-time contributors are Indian.',
    highlight: '25 LFX mentees have become CNCF project maintainers. The flywheel works.',
    links: { web: 'https://mentorship.lfx.linuxfoundation.org' },
  },
  {
    id: 'kubestronaut', name: 'Kubestronaut Program', symbol: 'Kb',
    category: 'education', city: 'national', org: 'CNCF',
    title: '478 Indian Kubestronauts of 4,427 globally · 42 Golden Kubestronauts of 519 globally',
    description: '~11% of all Kubestronauts worldwide are Indian (478 of 4,427). India has 42 Golden Kubestronauts out of 519 globally (~8%) — people who passed ALL 15 CNCF certs + LFCS.<br><br><b>🏅 Golden Kubestronauts by city:</b> Bengaluru (13) · Chennai/TN (9) · Pune (7) · Mumbai (5) · Delhi/NCR (3) · Kolkata (1) · Jaipur (1) · Nashik (1) · Kerala (1) · Odisha (1)<br><br><b>🚀 Kubestronauts by city:</b> Bengaluru (119) · Pune (55) · Hyderabad (43) · Delhi NCR (30) · Mumbai (29) · Chennai (24) · Kerala (10) · Ahmedabad (9) · Jaipur (5) · Kolkata (4)<br><br>Select "Kubestronauts by City" in the filter to see every name.',
    highlight: '42 Golden Kubestronauts from India — people who passed ALL 15 CNCF certifications. That\'s 8% of the world\'s Golden Kubestronauts.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'certifications', name: 'CNCF Certifications', symbol: 'Cr',
    category: 'education', city: 'national', org: 'CNCF / Linux Foundation',
    title: 'CKA, CKAD, CKS, KCNA, KCSA — India leading globally',
    description: 'Only 6% of Indian orgs report "not started" on CN adoption (vs 18% Japan). India has the highest cloud-native maturity score in Asia.',
    highlight: 'Only 6% of Indian organizations haven\'t started their cloud-native journey.',
    links: {},
  },
  {
    id: 'kodekloud', name: 'KodeKloud', symbol: 'Kk',
    category: 'education', city: 'national', org: 'Mumshad Mannambeth',
    title: '1M+ learners, CNCF-KodeKloud India training partnership',
    description: 'Founded by Mumshad Mannambeth (Indian-origin). 1M+ learners. CNCF-KodeKloud India training partnership (Aug 2025).',
    highlight: 'One million learners — KodeKloud made K8s education accessible.',
    links: { web: 'https://kodekloud.com' },
  },
  {
    id: 'cloudyuga', name: 'CloudYuga', symbol: 'CY',
    category: 'education', city: 'bangalore', org: 'Neependra Khare',
    title: 'LF training partner, organized India\'s first KCD',
    description: 'Founded by Neependra Khare (CNCF Ambassador). LF training partner. Organized India\'s first KCD (Bengaluru 2021).',
    highlight: 'Organized India\'s very first Kubernetes Community Day.',
    links: {},
  },
  {
    id: 'outreachy', name: 'Outreachy India', symbol: 'Ou',
    category: 'education', city: 'national', org: 'Outreachy',
    title: '5 confirmed Indian interns on CNCF projects',
    description: 'Prakriti Bansal (2018, Jaeger — India\'s first), Vishakha Nihore (2019), Harshita Srinivas (2021 → became mentor in 18 months!), Pridhi Arora (2022 — career re-entry after 5-year gap), sakshi (2023).',
    highlight: 'Harshita: intern in 2021, mentor by 2022. Pridhi: 5-year career gap, self-taught Python, got into OTel.',
    links: {},
  },

  // ────────────────────────────────────────────────────────
  //  🚀 KUBESTRONAUTS — by city (436 of 4,427 globally)
  //  All 5 K8s certifications · ~10% of global total
  // ────────────────────────────────────────────────────────
  {
    id: 'ks-bangalore', name: 'Kubestronauts — Bengaluru', symbol: 'SB',
    category: 'education', city: 'bangalore', org: 'CNCF',
    title: '119 Kubestronauts · More than most countries',
    description: '<b>🚀 119 Kubestronauts from Bengaluru</b> (verified from CNCF):<br><br>Yaswanth Mylamuri, Yash Gandhi, Vishal Singh Mehra, Vino Alex, Vijay Nag, Vijay V, Vedaraju Sai Krishna, Venkatesh, Vamsi Krishna Sethu, Vaidhiyanathan R, Umashankar Sankaranarayanan, Tarak Nath Sinha, Sunil Hari, Sunil Kumar Shetty, Suhel Multani, Sudarshan Km, Srinath Kesav Nallamalli, Shubham Pawar, Shivam Sourav Jha, Shivanathan Ganapathy, Shishir Khandelwal, Shirish Hirekodi, Shashank T, Sharath Chandra Balla, Sayed Imran, Sathishkumar Natesan, Saravanan R Seenivasan, Sankarshan Mukhopadhyay, Sanjit Kumar, Sameer Paranjpye, Samantha Deshpande, Salauddin Shaik, Sai Prasanna, Rishi Jain, Ripunjay Chauhan, Reshma Abdul Rahman, Ravishankar Chavare, Ravikiran Srinivasulu, Ravi Mishra, Rasik Jain, Rakshitha A C, Rakesh Korukonda, Prerana Kambli, Pranav Kumbhar, Ponraj, Neeraj Kumar Pandey, Naveen Chakravarthy Balasubramaniyan, Naseer Pasha Kaginelli, Narayan S, Munwar Shariff, Mohan V B, Mishana Shah, Md Rehan, Keshav Kushwaha, Karuna Kumari, Kandukuri Pradeep, Jain Abraham, Jayalakshmi V, Gv Lakshmi Narasimha Rao, Hemanth S, Gowtham Muthukrishnan, Gopikrishnan Sasikumar, Gokul B, Dhananjay Ghogre, Deepak Rai, Chirag Dave, Charanjit Singh, Bingi Narasimha Karthik, Biswarup Mukherjee, Arvind Kapse, Ashish Tiwari, Ashok N, Arunkumar Gururaj, Arnab Mitra, Anshul Gupta, Ankit Srivastava, Ananth Kumar Ede, Amit Yadav, Amitha Pulijala, Anil Kumar Gona, Achyutha Mithra, and more.',
    highlight: 'Bengaluru alone has 119 Kubestronauts — more than most entire countries.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-pune', name: 'Kubestronauts — Pune', symbol: 'SP',
    category: 'education', city: 'pune', org: 'CNCF',
    title: '55 Kubestronauts · Pune',
    description: '<b>🚀 55 Kubestronauts from Pune</b> (verified from CNCF):<br><br>Yash Vilas Mahakal, Waseem Ahammed T K, Vivek Dabas, Vishal Anarase, Vishwambar Manchewar, Vijay Rana, Unmesh Shailendra Kadam, Tabish Athar, Swapnil Patil, Swarup Kulkarni, Suraj Pudale, Sunil Mohite, Shubhangi Deshmukh, Shikha Priyedarshi, Shahzad Ali Ahmad, Sayan Kumar Moitra, Saumya Pruthi, Sanket Dhopeshwarkar, Sameer Mene, Sagar Utekar, Sachin Torane, Rutik Meshram, Rushikesh Butala, Rohit Yadav, Rajeev Singh, Rahul Chaudhari, Prateek Jain, Prathamesh Musale, Pooja Kamath, Pavan Joshi, Nithin Reddy Manda, Mohan Tupe, Mayur Tendulkar, Mangesh Lad, Mahim Agarwal, Krunal Amin, Ketan Kelkar, Kaivalya Koparkar, Jayesh Srivastava, Jaydeep Pokale, Harish Jain, Girish Pandey, Ganesh Koli, Chris Jaimon, Bharat Kunal, Bhagyashri Shinde, Avishkar Thakur, Ashutosh Bodake, Aravind Putrevu, Apurva Bhandari, Amay Jain, Amit Gujar, Aman Khandelia, Ajay Shelar, Abhijeet Singh.',
    highlight: '55 Kubestronauts from Pune — India\'s quiet certification powerhouse.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-hyderabad', name: 'Kubestronauts — Hyderabad', symbol: 'SH',
    category: 'education', city: 'hyderabad', org: 'CNCF',
    title: '43 Kubestronauts · Hyderabad',
    description: '<b>🚀 43 Kubestronauts from Hyderabad</b> (verified from CNCF):<br><br>Vishwa Nageshwar Kodumagulla, Vishnu Vardhan Duvuri, Tulasinadh Vaka, Tilak Raj Chandan, Thejo Bhanu Pratap Koonisetty, Sudha Koushik Bodla, Subham Saha, Subhash Chandra Budde, Sri Venkata Surya Teja Ayyagari, Sivananda Reddy Pothu, Shubham Kumar, Satish Murru, Saikrishna Gorantla, Ravichandra Cheetala, Ravi Teja Maddikuntla, Prithvi Naik, Pappu Praveen Kumar, Padma Sri, Nithin Naidu Maddilety, Naveen Kumar B, Mohan Konala, Mohammed Adnan Ali, Mahesh Gude, Lokesh Kannan, Kritika Singh, Harish Thota, Gurucharan Subramani, Devi Sai Srinivas Peri, Deepak Sharma, Chandrasekhar Narala, Bhupender Rajput, Bhaskar Naidu, Bhargav Patel, Ashish Rajan, Arun Kumar Ayyagari, Aravind Peddi, Anupam Bhandari, Ankit Tiwari, Aman Kumar, Aditya Kishore Mishra, Adnan Shaikh, Abhishek Koserwal, Abhijeet Kasurde.',
    highlight: '43 Kubestronauts from Hyderabad — the upcoming KubeCon 2026 host city.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-mumbai', name: 'Kubestronauts — Mumbai', symbol: 'SM',
    category: 'education', city: 'mumbai', org: 'CNCF',
    title: '29 Kubestronauts · Mumbai Metro',
    description: '<b>🚀 29 Kubestronauts from Mumbai metro</b> (verified from CNCF):<br><br>Yatin Puthran, Vivek Kumar Mishra, Vishwajeet Mishra, Talha Juikar, Sumir Broota, Shubham H. Chaudhari, Sanjay Sachdev, Rohit Ravirao Dalal, Rhegisan Jebas, Ratan Singh Kalakoti, Ramya D, Ramanuj Dad, Pratul Singh, Prathamesh More, Prasad Patole, Niranjan Desai, Mangesh Pachkale, Manmohan Mirkar, Labhesh Hase, Krishna Shah, Kiran Mane, Husain Bohra, Aman Pasi, Amey Gavane, Anand Sinha, Anil Lad, Anurag Pathak, Dhawal Jogi, Deepak Bhatia.',
    highlight: '29 Kubestronauts from India\'s financial capital.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-chennai', name: 'Kubestronauts — Chennai', symbol: 'SC',
    category: 'education', city: 'chennai', org: 'CNCF',
    title: '24 Kubestronauts · Chennai / Tamil Nadu',
    description: '<b>🚀 24 Kubestronauts from Chennai / Tamil Nadu</b> (verified from CNCF):<br><br>Vinothkumar Kuppusamy, Venkatesh Ravichandran, Thiyagarajan Elangovan, Thanigaivelan Sendoorpandiyan, Sujay Kumar J, Subash P, Shaenmugapriyan S, Sakthi Namasivayam, Roach A, Ragavendra Vigneshwaran R, Prabhu Jayakumar, Paramaguru Subramaniyam, Paranitharan Kalaiselvan, Oliver Paul K, Lavanya Anbalagan, Kumar Soundarajan, Kumaran K, Keba Stalin Britto J, Gnana Salten S, Dillibabu Sampath, Ashok M, Anand Shanmugam, Akhilesh Tiwari, Santhosh Nc.',
    highlight: '24 Kubestronauts from Tamil Nadu — not just Chennai.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-delhi', name: 'Kubestronauts — Delhi NCR', symbol: 'SD',
    category: 'education', city: 'delhi', org: 'CNCF',
    title: '30 Kubestronauts · Delhi + Noida + Gurugram',
    description: '<b>🚀 30 Kubestronauts from Delhi NCR</b> (verified from CNCF):<br><br>Vivek Yadav, Vinod Kumar, Sumit Kaur, Sourav Bera, Siddharth Sharma, Shubhasis Mathur, Shubham Gupta, Shubham Vashishtha, Sandeep Kumar Aggarwal, Sanchit Raj, Sahil Anand, Rishabh Singh, Ranjeet Singh, Rajneesh Kumar Jha, Preetu Sharma, Praveen Kumar, Pratap Singh, Prabhjot Singh Bharaj, Nitin Kaushik, Mohit Sharma, Mohd Atif Raza, Mayank Rawat, Manish Kumar, Kumar Ashwin, Himanshu Kumar, Harsh Gupta, Deepak Sharma, Avinash Reddy Paladugu, Aashish Chaurasiya, Abhinav Tiwari.',
    highlight: '30 Kubestronauts from the Delhi NCR region.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-ahmedabad', name: 'Kubestronauts — Ahmedabad', symbol: 'SA',
    category: 'education', city: 'ahmedabad', org: 'CNCF',
    title: '9 Kubestronauts · Ahmedabad',
    description: '<b>🚀 9 Kubestronauts from Ahmedabad</b> (verified from CNCF):<br><br>Saurabh Kadam, Sanket Tarun Shah, Sanjay Chauhan, Ronak Padhya, Kaivalya Shah, Ishan Mahadevia, Bhargav Parmar, Arvind Singh, Aditya Krishnakumar.',
    highlight: '9 Kubestronauts from Ahmedabad — Gujarat is growing!',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-kolkata', name: 'Kubestronauts — Kolkata', symbol: 'SK',
    category: 'education', city: 'kolkata', org: 'CNCF',
    title: '4 Kubestronauts · Kolkata',
    description: '<b>🚀 4 Kubestronauts from Kolkata</b> (verified from CNCF):<br><br>Suman Chakraborty, Sayantan Karmakar, Sanjoy Gorai, Rajat Agarwal.',
    highlight: '4 Kubestronauts from Kolkata — East India represents.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-jaipur', name: 'Kubestronauts — Jaipur', symbol: 'SJ',
    category: 'education', city: 'jaipur', org: 'CNCF',
    title: '5 Kubestronauts · Jaipur',
    description: '<b>🚀 5 Kubestronauts from Jaipur</b> (verified from CNCF):<br><br>Vikas Verma, Milind Verma, Gaurank Goyal, Anubhav Mandarwal, Aditya Pancholi.',
    highlight: '5 Kubestronauts from Jaipur — certifications don\'t need metros.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'ks-kerala', name: 'Kubestronauts — Kerala', symbol: 'SL',
    category: 'education', city: 'kerala', org: 'CNCF',
    title: '10 Kubestronauts · Kerala',
    description: '<b>🚀 10 Kubestronauts from Kerala</b> (verified from CNCF):<br><br>Unni P, Suneesh Kumar, Sreejith Anujan, Sanju Raj, Sachin K Vaikan, Joobin P Nihas, Hima Hussain, Hassim Naseef Mukkanni, Dhanesh Kumar, Ansil H.',
    highlight: '10 Kubestronauts from God\'s own country.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },

  // ────────────────────────────────────────────────────────
  //  🎯 INVISIBLE CONTRIBUTIONS — roles people don't see
  //  Program Committee, Release Team, Exam Developers, etc.
  // ────────────────────────────────────────────────────────
  {
    id: 'program-committee', name: 'KubeCon Program Committee', symbol: 'PC',
    category: 'leaders', city: 'national', org: 'CNCF',
    title: 'Indians reviewing, selecting, and shaping KubeCon talks',
    description: 'Multiple Indians serve on the KubeCon Program Committee every year — selecting talks, reviewing CFPs, and shaping what the world sees on stage. Known members: Hrittik Roy (Program Committee), Saiyam Pathak (KubeCon India 2026 Program Chair), Nikhita Raghunath (KubeCon Chair), Sonali Srivastava (KubeCon India 2026 Co-Chair), Atulpriya Sharma (KubeCon India 2025 Co-Chair).',
    highlight: 'Indians don\'t just speak at KubeCon — they decide what gets spoken about.',
    links: {},
  },
  {
    id: 'release-team', name: 'K8s Release Team — India', symbol: 'RT',
    category: 'leaders', city: 'national', org: 'Kubernetes',
    title: 'Indians shipping Kubernetes releases to the world',
    description: 'Multiple Indians on the K8s release team across versions:<br>• Priyanka Saggu — v1.29 Release Lead<br>• Vyom Yadav — v1.34 Release Lead<br>• Nabarun Pal — v1.21 Release Lead<br>• Satyam Soni — Release team since v1.30<br>• Arsh Sharma — v1.25 CI Signal Lead<br><br>Every K8s release that runs your production clusters has Indian fingerprints on it.',
    highlight: 'When Kubernetes ships a new version, Indian engineers are on the release team making it happen.',
    links: {},
  },
  {
    id: 'exam-developers', name: 'Certification Exam Developers', symbol: 'ED',
    category: 'education', city: 'national', org: 'CNCF / Linux Foundation',
    title: 'Indians writing the CKA, CKAD, CKS, KCNA exams',
    description: 'Indian contributors help develop and maintain CNCF certification exams. Divya Mohan co-created the KCNA exam. Fazlur Rahman Khan authors official CKA/CKAD/CKS courses at the Linux Foundation — the first LF technical trainer based in India.<br><br>The exams millions study for? Indians write them.',
    highlight: 'The CKA exam you studied for? Indians helped write it.',
    links: {},
  },
  {
    id: 'cfp-reviewers', name: 'CFP Reviewers & Speakers', symbol: 'CF',
    category: 'leaders', city: 'national', org: 'CNCF',
    title: 'Indians reviewing proposals and speaking at global conferences',
    description: 'Indians serve as CFP reviewers, track chairs, and speakers at KubeCon, IstioCon, PromCon, and other CNCF events. They review hundreds of proposals, mentor first-time speakers, and shape the global cloud-native conversation. This invisible work is what makes conferences inclusive and high-quality.',
    highlight: 'Behind every great KubeCon talk — there\'s a reviewer who made it better. Many are Indian.',
    links: {},
  },
  {
    id: 'sig-contributors', name: 'SIG & WG Contributors', symbol: 'WG',
    category: 'maintainers', city: 'national', org: 'Kubernetes',
    title: 'Indians contributing to K8s SIGs and Working Groups',
    description: 'Indians contribute across Kubernetes SIGs:<br>• SIG Architecture — Dims (Chair)<br>• SIG Storage — Hemant Kumar (Chair), Humble Chirammal<br>• SIG Instrumentation — Pranshu Srivastava (Co-Chair)<br>• SIG Docs — Divya Mohan (Co-Chair)<br>• SIG ContribEx — Nabarun Pal, Madhav Jivrajani<br>• SIG Node, SIG Network, SIG Auth — multiple Indian contributors<br><br>The governance layer of Kubernetes has deep Indian representation.',
    highlight: 'Indians chair 4+ Kubernetes SIGs — the working groups that decide how K8s evolves.',
    links: {},
  },
  {
    id: 'gsoc-mentors', name: 'GSoC & LFX Mentors from India', symbol: 'ME',
    category: 'education', city: 'national', org: 'CNCF / Google',
    title: 'Indians mentoring the next generation of contributors',
    description: 'India is #1 in GSoC participation AND has a growing mentor base:<br>• Shivay Lamba — GSoC Admin & Mentor (Jenkins, Kubeflow)<br>• Vyom Yadav — LFX mentor after being a mentee<br>• Harshita Srinivas — Outreachy intern in 2021, mentor by 2022<br>• Ronit Banerjee — GSoC Mentor at DBpedia<br>• Shivanshu Raj Shrivastava — GSoC Mentor<br><br>The flywheel: mentee → contributor → maintainer → mentor.',
    highlight: 'India doesn\'t just produce GSoC participants — it produces GSoC mentors.',
    links: {},
  },

  // ────────────────────────────────────────────────────────
  //  🏅 GOLDEN KUBESTRONAUTS — by city (42 total)
  //  All 15 CNCF certs + LFCS · 42 of 519 globally from India
  // ────────────────────────────────────────────────────────
  {
    id: 'gk-bangalore', name: 'Golden Kubestronauts — Bengaluru', symbol: 'GB',
    category: 'education', city: 'bangalore', org: 'CNCF',
    title: '13 Golden Kubestronauts · Karnataka region',
    description: '<b>🏅 13 Golden Kubestronauts from Karnataka:</b><br><br>• Achyutha Mithra — First Security Islami Bank<br>• Akash Singh — Sabi<br>• Bingi Narasimha Karthik — Adobe<br>• Keshav Kushwaha — AMD India<br>• Krishna Kumar U — Boeing India<br>• Pramodh Kumar M — DevTools <i>(Chikmagalur)</i><br>• Rahul Kumar — McKinsey<br>• Rakesh Korukonda — HPE<br>• Ramkumar Nagaraj — Adobe India<br>• Sayed Imran — Convin<br>• Vijay Nag — Morgan Stanley<br>• Vinay Kumar S G <i>(Shivamogga)</i><br>• Yaswanth Mylamuri — Mitsubishi Electric<br><br>Bengaluru alone has 116 Kubestronauts — more than most countries.',
    highlight: '13 Golden Kubestronauts from Karnataka — the most of any Indian state. Adobe, HPE, McKinsey, Morgan Stanley — world-class orgs, Indian talent.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-chennai', name: 'Golden Kubestronauts — Tamil Nadu', symbol: 'GT',
    category: 'education', city: 'chennai', org: 'CNCF',
    title: '9 Golden Kubestronauts · Tamil Nadu region',
    description: '<b>🏅 9 Golden Kubestronauts from Tamil Nadu:</b><br><br>• Ashok M — DigitalOcean <i>(Chennai)</i><br>• Dillibabu Sampath <i>(Chennai)</i><br>• Gnana Salten S — HPE <i>(Tirunelveli)</i><br>• Keba Stalin Britto J — HPE <i>(Paramakudi)</i><br>• Kumar Soundarajan — Fidelity Investments <i>(Chennai)</i><br>• Lavanya Anbalagan — Bedag Informatik <i>(Chennai)</i><br>• Mathivanan Anbalagan — SFEIR<br>• Paramaguru S — Archimedis Digital <i>(Chennai)</i><br>• Santhosh Nc — Thoughtworks <i>(Erode)</i><br><br>Not just Chennai — Golden Kubestronauts from Tirunelveli, Paramakudi, and Erode. Cloud native reaches deep into Tamil Nadu.',
    highlight: '9 Golden Kubestronauts from across Tamil Nadu — not just metros. Tirunelveli, Paramakudi, Erode — cloud native is everywhere.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-pune', name: 'Golden Kubestronauts — Pune', symbol: 'GP',
    category: 'education', city: 'pune', org: 'CNCF',
    title: '7 Golden Kubestronauts · Pune',
    description: '<b>🏅 7 Golden Kubestronauts from Pune:</b><br><br>• Chris Jaimon — Armor Defense<br>• Mayur Tendulkar — Rapid Circle<br>• Rahul Chaudhari<br>• <b>Sagar Utekar — CrowdStrike</b> 👈 <i>That\'s me!</i><br>• Sameer Mene — Persistent Systems<br>• Shikha Priyedarshi — Microsoft<br>• Vishal Anarase — Mirantis<br><br>Pune — India\'s quiet powerhouse. 7 people who passed ALL 15 CNCF certifications.',
    highlight: '7 Golden Kubestronauts from Pune — including your speaker today! CrowdStrike, Microsoft, Persistent Systems, Mirantis.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-mumbai', name: 'Golden Kubestronauts — Mumbai', symbol: 'GM',
    category: 'education', city: 'mumbai', org: 'CNCF',
    title: '5 Golden Kubestronauts · Mumbai Metro',
    description: '<b>🏅 5 Golden Kubestronauts from Mumbai Metro:</b><br><br>• Aman Pasi — Dassault Systemes <i>(Navi Mumbai)</i><br>• Labhesh Hase <i>(Mumbai)</i><br>• Manmohan Mirkar <i>(Thane)</i><br>• Sanjay Sachdev — Red Hat <i>(Mumbai)</i><br>• Vivek Kumar Mishra — Thoughtworks <i>(Mumbai)</i><br><br>Mumbai, Navi Mumbai, Thane — the financial capital is also a Golden Kubestronaut hub.',
    highlight: '5 Golden Kubestronauts from the Mumbai metro region — Red Hat, Dassault, Thoughtworks.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-delhi', name: 'Golden Kubestronauts — Delhi/NCR', symbol: 'GD',
    category: 'education', city: 'delhi', org: 'CNCF',
    title: '3 Golden Kubestronauts · Delhi NCR',
    description: '<b>🏅 3 Golden Kubestronauts from Delhi NCR:</b><br><br>• Aashish Chaurasiya — Vultr <i>(New Delhi)</i><br>• Sahil Anand — Microsoft <i>(New Delhi)</i><br>• Vivek Yadav — UKG <i>(Noida)</i><br><br>The national capital region with 3 Golden Kubestronauts across Delhi and Noida.',
    highlight: '3 Golden Kubestronauts in the Delhi NCR region — Vultr, Microsoft, UKG.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-kolkata', name: 'Golden Kubestronaut — Kolkata', symbol: 'GK',
    category: 'education', city: 'kolkata', org: 'CNCF',
    title: '1 Golden Kubestronaut · Kolkata',
    description: '<b>🏅 Golden Kubestronaut from Kolkata:</b><br><br>• Sayantan Karmakar — Motorola Solutions<br><br>East India\'s Golden Kubestronaut — proving cloud native thrives beyond the western and southern metros.',
    highlight: 'Kolkata\'s Golden Kubestronaut — Sayantan Karmakar at Motorola Solutions.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-jaipur', name: 'Golden Kubestronaut — Jaipur', symbol: 'GJ',
    category: 'education', city: 'jaipur', org: 'CNCF',
    title: '1 Golden Kubestronaut · Jaipur',
    description: '<b>🏅 Golden Kubestronaut from Jaipur:</b><br><br>• Vikas Verma<br><br>Rajasthan on the Golden Kubestronaut map. Tier-2 cities are rising.',
    highlight: 'Jaipur has a Golden Kubestronaut — cloud native doesn\'t live only in metros.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-nashik', name: 'Golden Kubestronaut — Nashik', symbol: 'GN',
    category: 'education', city: 'nashik', org: 'CNCF',
    title: '1 Golden Kubestronaut · Nashik',
    description: '<b>🏅 Golden Kubestronaut from Nashik:</b><br><br>• Umesh Pagar<br><br>A Golden Kubestronaut from Nashik — a Tier-2 city. ALL 15 CNCF certifications. This is the grassroots story.',
    highlight: 'Nashik has a Golden Kubestronaut — 15 certifications from a Tier-2 city.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-kerala', name: 'Golden Kubestronaut — Kerala', symbol: 'GL',
    category: 'education', city: 'kerala', org: 'CNCF',
    title: '1 Golden Kubestronaut · Kerala',
    description: '<b>🏅 Golden Kubestronaut from Kerala:</b><br><br>• Hassim Naseef Mukkanni — Nixora <i>(Kannur)</i><br><br>Not Kochi or Trivandrum — Kannur! Cloud native reaching every corner of Kerala.',
    highlight: 'A Golden Kubestronaut from Kannur, Kerala — not just the big cities.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },
  {
    id: 'gk-odisha', name: 'Golden Kubestronaut — Odisha', symbol: 'GO',
    category: 'education', city: 'national', org: 'CNCF',
    title: '1 Golden Kubestronaut · Rourkela, Odisha',
    description: '<b>🏅 Golden Kubestronaut from Odisha:</b><br><br>• Baikuntha Bana Bihari Sahoo — Lloyds Technology Centre <i>(Rourkela)</i><br><br>Rourkela, Odisha — a steel city with a Golden Kubestronaut. This is India\'s depth.',
    highlight: 'A Golden Kubestronaut from Rourkela, Odisha — India\'s cloud native depth.',
    links: { web: 'https://www.cncf.io/training/kubestronaut/' },
  },

  // ────────────────────────────────────────────────────────
  //  🩵 COMMUNITY & EVENTS
  // ────────────────────────────────────────────────────────
  {
    id: 'kubecon-india', name: 'KubeCon India', symbol: 'K4',
    category: 'community', city: 'national', org: 'CNCF',
    title: '4 editions · 4 cities · 3,200+ at Mumbai 2025',
    description: 'Bangalore (2023 KubeDay) → Delhi (2024) → Mumbai (2025, 3,200+, 60% first-timers) → Hyderabad (2026). Growing every year.',
    highlight: 'KubeCon India in 4 different cities. This isn\'t a one-city story.',
    links: {},
  },
  {
    id: 'kubecon-blr', name: 'KubeDay India 2023', symbol: 'KB',
    category: 'community', city: 'bangalore', org: 'CNCF',
    title: 'First KubeCon-style event in India · Bengaluru 2023',
    description: 'KubeDay India 2023 in Bengaluru — the event that started India\'s KubeCon journey. Where it all began.',
    highlight: 'Bengaluru — where India\'s KubeCon journey started.',
    links: {},
  },
  {
    id: 'kubecon-del', name: 'KubeCon India 2024', symbol: 'KD',
    category: 'community', city: 'delhi', org: 'CNCF',
    title: 'KubeCon + CloudNativeCon India · Delhi 2024',
    description: 'The first full KubeCon + CloudNativeCon India. Co-chaired by Nikhita Raghunath and Divya Mohan. Delhi NCR.',
    highlight: 'First full KubeCon India — co-chaired by two Indian women.',
    links: {},
  },
  {
    id: 'kubecon-mum', name: 'KubeCon India 2025', symbol: 'KM',
    category: 'community', city: 'mumbai', org: 'CNCF',
    title: '3,200+ attendees · 800 orgs · 60% first-timers · Mumbai 2025',
    description: '3,200+ attendees, 800 unique organizations, 60% first-timers. The largest cloud-native event in India to date.',
    highlight: '3,200 attendees, 60% first-timers — Mumbai 2025 proved India is hungry for cloud native.',
    links: {},
  },
  {
    id: 'kubecon-hyd', name: 'KubeCon India 2026', symbol: 'KH',
    category: 'community', city: 'hyderabad', org: 'CNCF',
    title: 'KubeCon + CloudNativeCon India · Hyderabad 2026',
    description: 'The next edition of KubeCon India — coming to Hyderabad.',
    highlight: 'KubeCon India keeps moving to new cities — Hyderabad is next.',
    links: {},
  },
  {
    id: 'ambassadors-stat', name: '42 CNCF Ambassadors', symbol: '42',
    category: 'community', city: 'national', org: 'CNCF',
    title: '42 confirmed CNCF Ambassadors from India',
    description: 'From TAG Chairs to chapter organizers, from Tier-1 cities to Nashik and Jaipur. The broadest ambassador network in Asia.',
    highlight: '42 ambassadors. Not just in metros — Nashik, Jaipur, Trivandrum, Ahmedabad.',
    links: {},
  },
  {
    id: 'chapters', name: '42 CNCF Chapters', symbol: 'Ch',
    category: 'community', city: 'national', org: 'CNCF',
    title: '42 chapters across 15 states — more than most countries combined',
    description: '<b>42 CNCF community groups across 15 Indian states</b> (source: <a href="https://cncg.in" target="_blank">cncg.in</a>):<br><br>🏆 <b>Maharashtra (8):</b> Mumbai, Pune, Thane, Nagpur, Nashik, Chhatrapati Sambhajinagar, Jalgaon, K8s Pune<br>🏆 <b>Gujarat (5):</b> Ahmedabad, Gandhinagar, Rajkot, Vadodara, Surat<br>🏆 <b>Tamil Nadu (5):</b> Chennai, Coimbatore, Tiruchirappalli, Madurai, Pollachi<br>🏆 <b>Kerala (5):</b> Kochi, Thiruvananthapuram, Kozhikode, Kottayam, Thrissur<br>• <b>Karnataka (3):</b> Bengaluru, Mysuru, Platform Eng Bengaluru<br>• <b>West Bengal (3):</b> Kolkata, Durgapur, Hooghly<br>• <b>Uttar Pradesh (3):</b> Lucknow, Noida, Kanpur<br>• <b>Rajasthan (2):</b> Jaipur, Bikaner<br>• <b>Delhi (2):</b> New Delhi, CN Security India<br>• <b>Telangana:</b> Hyderabad<br>• <b>Odisha:</b> Bhubaneswar<br>• <b>Chandigarh:</b> Chandigarh<br>• <b>Uttarakhand:</b> Dehradun<br>• <b>Haryana:</b> Gurugram<br>• <b>Jharkhand:</b> Ranchi',
    highlight: 'This isn\'t top-down. This is grassroots. 42 chapters in 15 states deciding they care. Gujarat alone has 5!',
    links: { web: 'https://cncg.in' },
  },
  {
    id: 'cncg-bangalore', name: 'CNCF Bengaluru Chapters', symbol: 'CB',
    category: 'community', city: 'bangalore', org: 'CNCF',
    title: '3 chapters: Bengaluru, Mysuru, Platform Eng Bengaluru + KCDs',
    description: '3 CNCF chapters in Karnataka (source: cncg.in). Bengaluru hosts regular monthly meetups, KCDs since 2021 (India\'s first KCD!), and is where KubeDay India 2023 was held.',
    highlight: 'India\'s first KCD happened in Bengaluru (2021). The city that kickstarted it all.',
    links: { web: 'https://bangalore.cncg.in' },
  },
  {
    id: 'cncg-pune', name: 'CNCF Pune Chapters', symbol: 'CP',
    category: 'community', city: 'pune', org: 'CNCF',
    title: '2 chapters: Pune, Kubernetes Pune + KCD Pune',
    description: '2 CNCF chapters (source: cncg.in): CNCF Pune and Kubernetes Pune. Regular meetups. KCD Pune has been held multiple times.',
    highlight: 'Pune — 2 CNCF chapters, regular meetups, and KCDs.',
    links: { web: 'https://pune.cncg.in' },
  },
  {
    id: 'cncg-mumbai', name: 'CNCF Mumbai & Thane', symbol: 'CM',
    category: 'community', city: 'mumbai', org: 'CNCF',
    title: '2 chapters: Mumbai, Thane + KCD Mumbai + KubeCon 2025',
    description: '2 CNCF chapters (source: cncg.in): Mumbai and Thane. KCD Mumbai held regularly. KubeCon India 2025 was hosted here with 3,200+ attendees.',
    highlight: 'Mumbai hosted India\'s biggest KubeCon with 3,200+ attendees.',
    links: { web: 'https://mumbai.cncg.in' },
  },
  {
    id: 'cncg-chennai', name: 'CNCF Tamil Nadu Chapters', symbol: 'CT',
    category: 'community', city: 'chennai', org: 'CNCF',
    title: '5 chapters: Chennai, Coimbatore, Trichy, Madurai, Pollachi',
    description: '5 CNCF chapters across Tamil Nadu (source: cncg.in). Chennai hosts regular meetups and KCDs. Cloud native reaching deep into the state — Pollachi and Trichy have their own chapters!',
    highlight: '5 CNCF chapters in Tamil Nadu alone — not just Chennai. Pollachi has a chapter!',
    links: { web: 'https://chennai.cncg.in' },
  },
  {
    id: 'cncg-delhi', name: 'CNCF Delhi NCR', symbol: 'CD',
    category: 'community', city: 'delhi', org: 'CNCF',
    title: '2 chapters: New Delhi, CN Security India + KubeCon 2024',
    description: '2 CNCF chapters (source: cncg.in): New Delhi and Cloud Native Security India (national chapter based in Delhi). KubeCon India 2024 was held here.',
    highlight: 'Delhi hosted the first full KubeCon India in 2024.',
    links: { web: 'https://new-delhi.cncg.in' },
  },
  {
    id: 'cncg-kerala', name: 'CNCF Kerala Chapters', symbol: 'CK',
    category: 'community', city: 'kerala', org: 'CNCF',
    title: '5 chapters: Kochi, Trivandrum, Kozhikode, Kottayam, Thrissur',
    description: '5 CNCF chapters across Kerala (source: cncg.in). KCD Kerala and DevOpsDays Kerala organized by Sreejith Anujan. 100+ events from the state.',
    highlight: '5 CNCF chapters in Kerala — cloud native from Kochi to Kozhikode.',
    links: { web: 'https://kochi.cncg.in' },
  },
  {
    id: 'cncg-kolkata', name: 'CNCF West Bengal Chapters', symbol: 'CW',
    category: 'community', city: 'kolkata', org: 'CNCF',
    title: '3 chapters: Kolkata, Durgapur, Hooghly',
    description: '3 CNCF chapters in West Bengal (source: cncg.in). Ronit Banerjee leads Cloud Native Hooghly. KCD Kolkata has been held.',
    highlight: '3 CNCF chapters in West Bengal — East India represents.',
    links: { web: 'https://kolkata.cncg.in' },
  },
  {
    id: 'cncg-hyderabad', name: 'CNCF Hyderabad', symbol: 'HY',
    category: 'community', city: 'hyderabad', org: 'CNCF',
    title: '1 chapter + KubeCon India 2026 host city',
    description: 'CNCF Hyderabad chapter (source: cncg.in). Organized by Atulpriya Sharma. KubeCon India 2026 will be hosted here.',
    highlight: 'Hyderabad is the next KubeCon India host city (2026).',
    links: { web: 'https://hyderabad.cncg.in' },
  },
  {
    id: 'cncg-jaipur', name: 'CNCF Rajasthan Chapters', symbol: 'CR',
    category: 'community', city: 'jaipur', org: 'CNCF',
    title: '2 chapters: Jaipur, Bikaner',
    description: '2 CNCF chapters in Rajasthan (source: cncg.in): Jaipur and Bikaner. Led by Swastik Gour and Aditya Soni.',
    highlight: 'Bikaner has a CNCF chapter — cloud native truly everywhere in India.',
    links: { web: 'https://jaipur.cncg.in' },
  },
  {
    id: 'cncg-chandigarh', name: 'CNCF Chandigarh', symbol: 'CC',
    category: 'community', city: 'chandigarh', org: 'CNCF',
    title: '1 chapter + regular meetups',
    description: 'CNCF Chandigarh chapter (source: cncg.in). Home to Saiyam Pathak (TAG Chair), Vyom Yadav (K8s Release Lead), and Arsh Sharma.',
    highlight: 'Chandigarh — small city, massive cloud-native output.',
    links: { web: 'https://chandigarh.cncg.in' },
  },
  {
    id: 'kcds', name: '15+ KCDs in India', symbol: '15',
    category: 'community', city: 'national', org: 'CNCF',
    title: 'Kubernetes Community Days in 15+ Indian cities',
    description: 'KCDs in Bangalore, Mumbai, Delhi, Chennai, Pune, Ahmedabad (KCD Gujarat 2026!), Hyderabad, Kolkata, and more.',
    highlight: 'KCD Gujarat is happening right here, right now. You are the community.',
    links: {},
  },
  {
    id: 'kcd-gujarat', name: 'KCD Gujarat 2026', symbol: 'KG',
    category: 'community', city: 'ahmedabad', org: 'CNCF',
    title: 'Ahmedabad · Sep 19, 2026 · You are here! 🎉',
    description: 'The first Kubernetes Community Day in Gujarat. Bringing cloud native to western India. Gujarat has 5 CNCF chapters: Ahmedabad, Gandhinagar, Rajkot, Vadodara, Surat.',
    highlight: 'The fact that you\'re sitting here means Gujarat is officially on the cloud-native map.',
    links: {},
  },
  {
    id: 'cn-ahmedabad', name: 'CNCF Gujarat Chapters', symbol: 'CG',
    category: 'community', city: 'ahmedabad', org: 'CNCF Chapter',
    title: '5 chapters: Ahmedabad, Gandhinagar, Rajkot, Vadodara, Surat',
    description: '5 CNCF community groups in Gujarat (source: cncg.in): Ahmedabad, Gandhinagar, Rajkot, Vadodara, Surat. The most chapters in any western Indian state.',
    highlight: 'Gujarat has 5 CNCF chapters — more than most countries.',
    links: { web: 'https://ahmedabad.cncg.in' },
  },
  {
    id: 'cncg-nashik', name: 'CNCF Nashik', symbol: 'CN',
    category: 'community', city: 'nashik', org: 'CNCF',
    title: '1 chapter · founded by Kaiwalya Koparkar',
    description: 'CNCF Nashik chapter (source: cncg.in). Founded by Kaiwalya Koparkar. A Tier-2 city with its own CNCF chapter.',
    highlight: 'Nashik — proof that cloud native doesn\'t need a metro city.',
    links: { web: 'https://nashik.cncg.in' },
  },

  // ────────────────────────────────────────────────────────
  //  🩷 DIVERSITY & INCLUSION
  // ────────────────────────────────────────────────────────
  {
    id: 'wicn', name: 'Women in Cloud Native', symbol: 'Wi',
    category: 'diversity', city: 'national', org: 'CNCF Community Group',
    title: 'Led by Sonali Srivastava (InfraCloud), strong India presence',
    description: 'Sonali Srivastava co-chairs KubeCon India AND leads WiCN globally. Shikha Priyedarshi (Pune) — Kubestronaut. Growing community across India.',
    highlight: 'The best ecosystems aren\'t just big. They\'re inclusive.',
    links: {},
  },
  {
    id: 'dhhc', name: 'DHHC Community', symbol: 'DH',
    category: 'diversity', city: 'national', org: 'CNCF',
    title: 'Deaf and Hard of Hearing Community — accessibility in cloud native',
    description: 'CNCF DHHC community group. Making cloud native accessible to everyone.',
    highlight: 'Inclusion means everyone — including the Deaf and Hard of Hearing community.',
    links: {},
  },
  {
    id: 'scholarships', name: 'KubeCon Diversity Scholarships', symbol: 'DS',
    category: 'diversity', city: 'national', org: 'CNCF / Dan Kohn Fund',
    title: 'Funding Indian attendees to participate in KubeCon',
    description: 'KubeCon diversity scholarships and Dan Kohn Scholarship. Enabling access for underrepresented communities.',
    highlight: 'Removing barriers — because the next Nikhita might not afford a conference ticket.',
    links: {},
  },

  // ────────────────────────────────────────────────────────
  //  Additional notable people (from PPTX + research)
  // ────────────────────────────────────────────────────────
  {
    id: 'neependra', name: 'Neependra Khare', symbol: 'Nk',
    category: 'education', city: 'bangalore', org: 'CloudYuga',
    title: 'CloudYuga founder, organized India\'s first KCD',
    description: 'CNCF Ambassador. LF training partner. Organized India\'s first KCD (Bengaluru 2021). Has been training India\'s cloud-native workforce for years.',
    highlight: 'The person who organized India\'s very first Kubernetes Community Day.',
    links: {},
  },
  {
    id: 'kubesimplify', name: 'Kubesimplify', symbol: 'Ks',
    category: 'education', city: 'chandigarh', org: 'Saiyam Pathak + Saloni Narang',
    title: '100K+ community, 50K+ YouTube, 5 open-source tools',
    description: 'Founded by Saiyam Pathak. Co-run with Saloni Narang. 5 open-source tools: KIAC, SRELens, kubectl-upgrade, ing-switch, memwarden.',
    highlight: '100,000+ people learning cloud native — from Chandigarh.',
    links: { web: 'https://kubesimplify.com' },
  },
  {
    id: 'raj-das', name: 'Raj Babu Das', symbol: 'Rd',
    category: 'ambassadors', city: 'national', org: 'Harness',
    title: 'LitmusChaos maintainer, Prometheus/Kyverno contributor',
    description: 'CNCF Ambassador. Multi-project contributor spanning LitmusChaos, Prometheus, Kyverno, and SigNoz.',
    highlight: 'Contributing across 4+ CNCF projects simultaneously.',
    links: {},
  },
  {
    id: 'prithvi', name: 'Prithvi Raj', symbol: 'Pr',
    category: 'ambassadors', city: 'national', org: 'Mirantis',
    title: 'Scaled LitmusChaos community to 3,000+, OSPO lead',
    description: 'Led LitmusChaos community growth to 3,000+ members. Now OSPO lead at Mirantis OSS.',
    highlight: 'Grew LitmusChaos community from ground zero to 3,000+.',
    links: {},
  },
  {
    id: 'satyam', name: 'Satyam Soni', symbol: 'Sy',
    category: 'ambassadors', city: 'delhi', org: 'Devtron',
    title: 'K8s release team since v1.30',
    description: 'CNCF Ambassador. On the K8s release team since v1.30.',
    highlight: 'Shipping Kubernetes releases from India.',
    links: {},
  },
  {
    id: 'shivanshu', name: 'Shivanshu Raj Shrivastava', symbol: 'Si',
    category: 'ambassadors', city: 'national', org: 'SigNoz',
    title: 'OTel/K8s/Istio contributor, GSoC mentor, KubeCon speaker',
    description: 'Works at SigNoz (YC-W21). OpenTelemetry, Kubernetes, and Istio contributor. GSoC mentor. IstioCon + KubeCon speaker.',
    highlight: 'From SigNoz contributor to KubeCon stage.',
    links: {},
  },
  {
    id: 'rajas', name: 'Rajas Kakodkar', symbol: 'Rk',
    category: 'maintainers', city: 'bangalore', org: 'Broadcom',
    title: 'CNCF TAG Tech Lead, K8s Release Team',
    description: 'Software Engineer at Broadcom. CNCF TAG tech lead. Active in Kubernetes Release Team and SIG Release. Contour contributor.',
    highlight: 'From contributor to TAG tech lead — proving Indians don\'t just use K8s, they ship it.',
    links: { github: 'rajaskakodkar' },
  },
  {
    id: 'dipesh', name: 'Dipesh Rawat', symbol: 'Dr',
    category: 'leaders', city: 'national', org: 'IBM',
    title: 'K8s v1.37 Release Lead, SIG Docs Tech Lead, CNCF Ambassador',
    description: 'Kubernetes v1.37 Release Lead — the person steering the next K8s release. Release Team member since v1.31. SIG Docs Tech Lead. CNCF Ambassador and Kubestronaut. Software Developer at IBM.',
    highlight: 'From Release Team member to Release Lead in 6 versions — that\'s what showing up consistently looks like.',
    links: { github: 'dipesh-rawat', twitter: 'dipesh_rawat' },
  },
  {
    id: 'sreeram', name: 'Sreeram Venkitesh', symbol: 'Sv',
    category: 'leaders', city: 'national', org: 'DigitalOcean',
    title: 'K8s v1.31 Enhancements Lead, Release Team v1.29-v1.35',
    description: 'Kubernetes v1.31 Enhancements Lead — managed 100+ feature enhancements through a major release. 7 consecutive K8s releases on the release team (v1.29-v1.35). LWKD newsletter contributor for 2+ years. 20+ talks across 6 countries including KubeCon EU. Senior SWE at DigitalOcean (Managed K8s). From Kerala.',
    highlight: '7 consecutive Kubernetes releases on the release team, from Kerala to KubeCon stages worldwide.',
    links: { github: 'sreeram-venkitesh', twitter: 'sreeramvnkitesh' },
  },
  {
    id: 'rajani', name: 'Rajani Ekunde', symbol: 'Re',
    category: 'leaders', city: 'bangalore', org: 'GlobalLogic',
    description: 'Senior SRE at GlobalLogic, Bengaluru. AWS Community Builder. Creator of 90DaysOfDevOps repo (73+ stars). Writes on eBPF observability, cloud security with Neo4j, and AI agents for infrastructure ops. Ex-TCS.',
    highlight: 'From TCS to building eBPF observability tools and cloud security graphs — the next generation of Indian SREs.',
    links: { github: 'rajani103', twitter: 'misalpav' },
  },
  // ── Missing ambassadors from official CNCF list (42 total for India) ──
  {
    id: 'aakansha-priya', name: 'Aakansha Priya', symbol: 'Ap',
    category: 'ambassadors', city: 'delhi', org: 'EmpathyOps',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Community builder focused on empathy-driven operations and cloud native advocacy.',
    links: {},
  },
  {
    id: 'abhinav-dubey', name: 'Abhinav Dubey', symbol: 'Ad',
    category: 'ambassadors', city: 'delhi', org: 'Devtron Inc',
    title: 'CNCF Ambassador, Devtron',
    description: 'CNCF Ambassador at Devtron. Advocates for Kubernetes-native application delivery and developer experience.',
    links: {},
  },
  {
    id: 'afzal-ansari', name: 'Afzal Ansari', symbol: 'Aa',
    category: 'ambassadors', city: 'national', org: 'Akuity',
    title: 'CNCF Ambassador, Akuity',
    description: 'CNCF Ambassador at Akuity. Active in GitOps and Argo ecosystem advocacy.',
    links: {},
  },
  {
    id: 'ankit-kumar', name: 'Ankit Kumar', symbol: 'Ak',
    category: 'ambassadors', city: 'delhi', org: 'Fine AI',
    title: 'CNCF Ambassador, Fine AI',
    description: 'CNCF Ambassador at Fine AI. Works on cloud native AI infrastructure and community education.',
    links: {},
  },
  {
    id: 'anurag-kumar', name: 'Anurag Kumar', symbol: 'An',
    category: 'ambassadors', city: 'kolkata', org: 'Independent',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Cloud native community advocate and educator.',
    links: {},
  },
  {
    id: 'faeka-ansari', name: 'Faeka Ansari', symbol: 'Fa',
    category: 'ambassadors', city: 'pune', org: 'Independent',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Community builder and cloud native advocate.',
    links: {},
  },
  {
    id: 'humble-chirammal', name: 'Humble Devassy Chirammal', symbol: 'Hc',
    category: 'ambassadors', city: 'kerala', org: 'Independent',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Long-time Kubernetes and container ecosystem contributor.',
    links: {},
  },
  {
    id: 'leon-nunes', name: 'Leon Nunes', symbol: 'Ln',
    category: 'ambassadors', city: 'mumbai', org: 'Independent',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Cloud native advocate and community educator.',
    links: {},
  },
  {
    id: 'monika-rajput', name: 'Monika Rajput', symbol: 'Mr',
    category: 'ambassadors', city: 'delhi', org: 'Ahead',
    title: 'CNCF Ambassador, Ahead',
    description: 'CNCF Ambassador at Ahead. Advocates for women in cloud native and Kubernetes adoption.',
    links: {},
  },
  {
    id: 'nitish-kumar', name: 'Nitish Kumar', symbol: 'Nk',
    category: 'ambassadors', city: 'chandigarh', org: 'Independent',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Active in cloud native community building and education.',
    links: {},
  },
  {
    id: 'pradyumna-krishna', name: 'Pradyumna Krishna', symbol: 'Pk',
    category: 'ambassadors', city: 'delhi', org: 'Banaras Hindu University',
    title: 'CNCF Ambassador, Student',
    description: 'CNCF Ambassador and student at Banaras Hindu University. One of the youngest Indian ambassadors driving campus cloud native adoption.',
    links: {},
  },
  {
    id: 'pranshu-srivastava', name: 'Pranshu Srivastava', symbol: 'Ps',
    category: 'ambassadors', city: 'bangalore', org: 'Red Hat',
    title: 'CNCF Ambassador, Red Hat',
    description: 'CNCF Ambassador at Red Hat. Contributes to Kubernetes ecosystem and community education.',
    links: {},
  },
  {
    id: 'sandipan-panda', name: 'Sandipan Panda', symbol: 'Sp',
    category: 'ambassadors', city: 'kolkata', org: 'Independent',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Active in cloud native community building, DevOps, and Kubernetes advocacy.',
    links: {},
  },
  {
    id: 'seema-saharan', name: 'Seema Saharan', symbol: 'Ss',
    category: 'ambassadors', city: 'bangalore', org: 'Autodesk',
    title: 'CNCF Ambassador, Autodesk',
    description: 'CNCF Ambassador at Autodesk. Advocates for women in tech, Kubernetes, and cloud native adoption at enterprise scale.',
    links: {},
  },
  {
    id: 'vyom-yadav', name: 'Vyom Yadav', symbol: 'Vy',
    category: 'ambassadors', city: 'chandigarh', org: 'Independent',
    title: 'CNCF Ambassador',
    description: 'CNCF Ambassador. Active contributor to Kubernetes and cloud native security projects.',
    links: {},
  },
];

// ═══════════════════════════════════════════════════════════
//  PERIODIC TABLE — 7 cols × 7 rows (including header)
//  Matches the PPTX layout for KCD Gujarat 2026
//  Each cell is an entity ID or null for empty
// ═══════════════════════════════════════════════════════════

const PERIODIC_TABLE = [
  // Row 0:  Leaders    Maintainers  Projects     Ambassadors  Companies    Education    Community
  ['nikhita',      'vyom',         'kyverno',      'saiyam',       'infracloud',   'gsoc',         'kubecon-india'],
  // Row 1
  ['nabarun',      'sanskar',      'litmuschaos',  'hrittik',      'nirmata',      'lfx',          'ambassadors-stat'],
  // Row 2
  ['priyanka-saggu','vishal',      'kubearmor',    'rohit-ghumare','flipkart',     'kubestronaut', 'chapters'],
  // Row 3
  ['faseela',      'pranshu',      'openebs',      'yash-pimple',  'razorpay',     'certifications','kcds'],
  // Row 4
  ['dims',         'ganesh',       'devtron',      'arsh',         'hasura',       'kodekloud',    'wicn'],
  // Row 5
  ['humble',       'rohit-agrawal','parseable',    'barun',        'zerodha',      'cloudyuga',    'dhhc'],
];

// Verify data integrity on load
console.log(`✅ Loaded ${ENTITIES.length} entities across ${Object.keys(CATEGORIES).length} categories and ${Object.keys(CITIES).length - 1} cities + national`);
const catCounts = {};
ENTITIES.forEach(e => { catCounts[e.category] = (catCounts[e.category] || 0) + 1; });
Object.entries(catCounts).forEach(([k, v]) => console.log(`   ${CATEGORIES[k]?.icon || '?'} ${k}: ${v}`));
